# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('RStudioAsCppEditor_rcpp_hello', PACKAGE = 'RStudioAsCppEditor')
}

timesTwo <- function(x) {
    .Call('RStudioAsCppEditor_timesTwo', PACKAGE = 'RStudioAsCppEditor', x)
}

vecSquare <- function(x) {
    .Call('RStudioAsCppEditor_vecSquare', PACKAGE = 'RStudioAsCppEditor', x)
}

